# Generated by Django 4.0.6 on 2022-08-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coount',
            field=models.IntegerField(null=True),
        ),
    ]
