# Generated by Django 4.0.6 on 2022-08-31 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0002_post_coount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='coount',
            new_name='count',
        ),
    ]
