# Generated by Django 4.0.6 on 2022-08-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0003_rename_coount_post_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
